---
version: "3.4"
services:
  build:
    build:
      context: .
      target: build
    command: npm run build
    volumes:
      - .:/root/
  web:
    build:
      context: .
    ports:
      - "1313:1313"
    volumes:
      - .:/srv/hugo/
