---
version: "3.4"
services:
  build:
    build:
      context: .
      target: build
    command: bash -c "npm ci && npm run watch"
    volumes:
      - .:/root/
  web:
    build:
      context: .
    ports:
      - "1313:1313"
    volumes:
      - .:/root/
