---
version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo
    branches:
      only:
        - master
    steps:
      - checkout
      - add_ssh_keys
      - run: npm install
      - run: hugo
      - deploy:
          command: |
            echo 'cloud-vogler-07.nine.ch ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDlwuYlYQrXqev3g/E+rXL07scLXOLl2P3agNDsmwfT45OTeYx4hnxDyzy1oUytdW0U3seGW3WpKyYdchpILxB29hgviVlVoNbtoanGwoz9AGEKTQZgGiWrOsZ7mlxfDIj2nSgTPubkUFL4oOQVsNupBLnJgVtyIKTW14FipOYdjNZ8sltAdsZXoCDPiPtnqH7Bw4ysbpLZNXlhNgT92rCKSDYfpv+D6YQFKlNKZAih70mgNfqvnNljxXWW3BOyHS+iPWWbfHsRTCtpmLODzUusF6n/CU/EkK/5D1YggDel7jjgDEtdZB1iUmNpgh1qNbCJyAv0n3dP3dCgSKCsbnKT' >> ~/.ssh/known_hosts
            rsync -avz --delete public/ debian@cloud-vogler-07.nine.ch:/var/www/amgetu/2019
